-- schema.sql

-- 1. Brands
CREATE TABLE brands (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Customers (Shared identity across brands)
-- Design decision: Customers are decoupled from brands to allow a single identity.
-- If a customer interacts with a specific brand, that relationship is implicitly
-- maintained through orders, or we could add a `brand_customers` mapping table if
-- explicit marketing consent per brand is needed. For now, orders suffice.
CREATE TABLE customers (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    phone VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Products (Catalogue for each brand)
CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    brand_id INTEGER NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(100) UNIQUE NOT NULL,
    category VARCHAR(100),
    price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Orders (Belongs to a brand, linked to shared customer)
CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    brand_id INTEGER NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
    customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending'
);

-- Order Items (Linking orders to products)
CREATE TABLE order_items (
    id SERIAL PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products(id),
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL
);

-- 5. Raw Materials
CREATE TABLE raw_materials (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    unit_of_measure VARCHAR(50) NOT NULL,
    current_stock_quantity DECIMAL(10, 2) DEFAULT 0,
    reorder_level DECIMAL(10, 2) DEFAULT 0,
    cost_per_unit DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Formulations (Product recipes - linking products and raw materials)
CREATE TABLE product_formulations (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    raw_material_id INTEGER NOT NULL REFERENCES raw_materials(id) ON DELETE CASCADE,
    quantity_required DECIMAL(10, 4) NOT NULL,
    UNIQUE(product_id, raw_material_id)
);

-- ==========================================
-- CROSS-TASK CONSISTENCY TABLES
-- ==========================================

-- 7. Task 3 Requirement: Price Comparisons (Scraper)
-- Design decision: Stores scraped competitor data. We include previous_price
-- and price_changed boolean to easily flag changes on subsequent scrapes.
CREATE TABLE price_comparisons (
    id SERIAL PRIMARY KEY,
    search_term VARCHAR(255),
    product_name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2),
    seller_supplier VARCHAR(255),
    url TEXT,
    date_scraped TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    price_changed BOOLEAN DEFAULT FALSE,
    previous_price DECIMAL(10, 2)
);

-- 8. Task 4 Requirement: Product Reviews (Shopify App)
-- Design decision: Linked to `products(sku)` as requested. Included `ai_summary`
-- to cache the one-sentence AI summary generated by the Claude API, reducing API calls.
CREATE TABLE product_reviews (
    id SERIAL PRIMARY KEY,
    product_sku VARCHAR(100) NOT NULL REFERENCES products(sku) ON DELETE CASCADE,
    customer_name VARCHAR(255),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    ai_summary TEXT, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_products_brand_id ON products(brand_id);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_brand_id ON orders(brand_id);
CREATE INDEX idx_product_formulations_product_id ON product_formulations(product_id);
CREATE INDEX idx_product_reviews_product_sku ON product_reviews(product_sku);
